const translations = {
    'zh-TW': {
        'home': '首頁',
        'features': '功能介紹',
        'feedback': '用戶反饋',
        'download': '立即下載',
        'privacy': '隱私政策',
        'language': '語言',
        'hero_title': '讓數字學習變得簡單又有趣',
        'hero_subtitle': '專為兒童設計的數字學習應用，透過互動遊戲和練習，培養孩子對數學的興趣和信心',
        'core_features': '核心功能',
        'interactive_games': '互動學習遊戲',
        'interactive_games_desc': '透過有趣的遊戲方式學習數字，讓孩子愛上數學',
        'progress_tracking': '進度追蹤',
        'progress_tracking_desc': '詳細記錄學習進度，清晰掌握孩子的學習情況',
        'staged_learning': '階段式學習',
        'staged_learning_desc': '從基礎到進階，循序漸進地提高數學能力',
        'personalized_learning': '個性化學習',
        'personalized_learning_desc': '根據孩子的學習情況，自動調整難度和內容',
        'app_screenshots': '應用截圖',
        'feature_demo': '功能演示',
        'footer_rights': '© 2025 LearnNumber. 保留所有權利。',
        'quick_links': '快速連結',
        'contact_us': '聯絡我們',
        'product_title': 'LearnNumber 功能介紹',
        'product_subtitle': '探索 LearnNumber 的強大功能，讓您的孩子愛上數學',
        'feature_1_title': '互動式學習',
        'feature_1_desc': '透過生動有趣的遊戲，讓學習變得輕鬆愉快',
        'feature_2_title': '進度追蹤',
        'feature_2_desc': '詳細記錄學習進度，幫助家長了解孩子的學習情況',
        'feature_3_title': '個性化學習',
        'feature_3_desc': '根據孩子的學習情況，自動調整難度和內容',
        'feature_4_title': '豐富的練習題',
        'feature_4_desc': '提供多樣化的練習題，鞏固學習成果',
        'download_title': '立即下載 LearnNumber',
        'download_subtitle': '開始您的數學學習之旅',
        'download_ios': 'App Store 下載',
        'download_android': 'Google Play 下載',
        'system_requirements': '系統需求',
        'ios_requirements': 'iOS 13.0 或更高版本',
        'android_requirements': 'Android 8.0 或更高版本',
        'download_guide': '下載指南',
        'download_guide_desc': '按照以下步驟下載並安裝 LearnNumber',
        'feedback_title': '用戶反饋',
        'feedback_subtitle': '聽聽其他用戶的使用體驗',
        'write_review': '撰寫評價',
        'user_reviews': '用戶評價',
        'rating': '評分',
        'review_title': '評價標題',
        'review_content': '評價內容',
        'submit_review': '提交評價',
        'privacy_title': '隱私政策',
        'privacy_last_updated': '最後更新日期',
        'privacy_intro': '我們重視您的隱私',
        'privacy_collection': '資料收集',
        'privacy_usage': '資料使用',
        'privacy_protection': '資料保護',
        'privacy_rights': '用戶權利',
        'privacy_contact': '聯絡我們'
    },
    'zh-CN': {
        'home': '首页',
        'features': '功能介绍',
        'feedback': '用户反馈',
        'download': '立即下载',
        'privacy': '隐私政策',
        'language': '语言',
        'hero_title': '让数字学习变得简单有趣',
        'hero_subtitle': '专为儿童设计的数字学习应用，通过互动游戏和练习，培养孩子对数学的兴趣和信心',
        'core_features': '核心功能',
        'interactive_games': '互动学习游戏',
        'interactive_games_desc': '通过有趣的游戏方式学习数字，让孩子爱上数学',
        'progress_tracking': '进度追踪',
        'progress_tracking_desc': '详细记录学习进度，清晰掌握孩子的学习情况',
        'staged_learning': '阶段性学习',
        'staged_learning_desc': '从基础到进阶，循序渐进地提高数学能力',
        'personalized_learning': '个性化学习',
        'personalized_learning_desc': '根据孩子的学习情况，自动调整难度和内容',
        'app_screenshots': '应用截图',
        'feature_demo': '功能演示',
        'footer_rights': '© 2025 LearnNumber. 保留所有权利。',
        'quick_links': '快速链接',
        'contact_us': '联系我们',
        'product_title': 'LearnNumber 功能介绍',
        'product_subtitle': '探索 LearnNumber 的强大功能，让您的孩子爱上数学',
        'feature_1_title': '互动式学习',
        'feature_1_desc': '通过生动有趣的游戏，让学习变得轻松愉快',
        'feature_2_title': '进度追踪',
        'feature_2_desc': '详细记录学习进度，帮助家长了解孩子的学习情况',
        'feature_3_title': '个性化学习',
        'feature_3_desc': '根据孩子的学习情况，自动调整难度和内容',
        'feature_4_title': '丰富的练习题',
        'feature_4_desc': '提供多样化的练习题，巩固学习成果',
        'download_title': '立即下载 LearnNumber',
        'download_subtitle': '开始您的数学学习之旅',
        'download_ios': 'App Store 下载',
        'download_android': 'Google Play 下载',
        'system_requirements': '系统需求',
        'ios_requirements': 'iOS 13.0 或更高版本',
        'android_requirements': 'Android 8.0 或更高版本',
        'download_guide': '下载指南',
        'download_guide_desc': '按照以下步骤下载并安装 LearnNumber',
        'feedback_title': '用户反馈',
        'feedback_subtitle': '听听其他用户的使用体验',
        'write_review': '撰写评价',
        'user_reviews': '用户评价',
        'rating': '评分',
        'review_title': '评价标题',
        'review_content': '评价内容',
        'submit_review': '提交评价',
        'privacy_title': '隐私政策',
        'privacy_last_updated': '最后更新日期',
        'privacy_intro': '我们重视您的隐私',
        'privacy_collection': '资料收集',
        'privacy_usage': '资料使用',
        'privacy_protection': '资料保护',
        'privacy_rights': '用户权利',
        'privacy_contact': '联系我们'
    },
    'en': {
        'home': 'Home',
        'features': 'Features',
        'feedback': 'Feedback',
        'download': 'Download',
        'privacy': 'Privacy',
        'language': 'Language',
        'hero_title': 'Make Number Learning Simple and Fun',
        'hero_subtitle': 'A number learning app designed for children, cultivating interest and confidence in mathematics through interactive games and exercises',
        'core_features': 'Core Features',
        'interactive_games': 'Interactive Learning Games',
        'interactive_games_desc': 'Learn numbers through fun games, making children fall in love with math',
        'progress_tracking': 'Progress Tracking',
        'progress_tracking_desc': 'Detailed learning progress records, clearly understanding your child\'s learning situation',
        'staged_learning': 'Staged Learning',
        'staged_learning_desc': 'Progress from basic to advanced, gradually improving mathematical abilities',
        'personalized_learning': 'Personalized Learning',
        'personalized_learning_desc': 'Automatically adjust difficulty and content based on your child\'s learning situation',
        'app_screenshots': 'App Screenshots',
        'feature_demo': 'Feature Demo',
        'footer_rights': '© 2025 LearnNumber. All rights reserved.',
        'quick_links': 'Quick Links',
        'contact_us': 'Contact Us',
        'product_title': 'LearnNumber Features',
        'product_subtitle': 'Explore the powerful features of LearnNumber and make your child fall in love with math',
        'feature_1_title': 'Interactive Learning',
        'feature_1_desc': 'Make learning enjoyable through engaging games',
        'feature_2_title': 'Progress Tracking',
        'feature_2_desc': 'Detailed progress records to help parents understand their child\'s learning situation',
        'feature_3_title': 'Personalized Learning',
        'feature_3_desc': 'Automatically adjust difficulty and content based on your child\'s learning situation',
        'feature_4_title': 'Rich Exercise Content',
        'feature_4_desc': 'Provide diverse exercises to consolidate learning results',
        'download_title': 'Download LearnNumber Now',
        'download_subtitle': 'Start Your Math Learning Journey',
        'download_ios': 'Download on App Store',
        'download_android': 'Download on Google Play',
        'system_requirements': 'System Requirements',
        'ios_requirements': 'iOS 13.0 or later',
        'android_requirements': 'Android 8.0 or later',
        'download_guide': 'Download Guide',
        'download_guide_desc': 'Follow these steps to download and install LearnNumber',
        'feedback_title': 'User Feedback',
        'feedback_subtitle': 'Hear from other users about their experience',
        'write_review': 'Write a Review',
        'user_reviews': 'User Reviews',
        'rating': 'Rating',
        'review_title': 'Review Title',
        'review_content': 'Review Content',
        'submit_review': 'Submit Review',
        'privacy_title': 'Privacy Policy',
        'privacy_last_updated': 'Last Updated',
        'privacy_intro': 'We Value Your Privacy',
        'privacy_collection': 'Data Collection',
        'privacy_usage': 'Data Usage',
        'privacy_protection': 'Data Protection',
        'privacy_rights': 'User Rights',
        'privacy_contact': 'Contact Us'
    }
}; 